use strict;
use warnings;
use v5.10;
package FileToList;
use Carp qw(confess);

=head
Given a file, return its lines as a list.
To be used for single column with no spaces.
The returned list is generated by splitting on new lines.
=cut
sub new {
    my $class = shift;
    my $full_file_path = shift;
    my $self = {};
    $self->{full_file_path} = $full_file_path;
    bless $self, $class;
    return $self;
}
# Check that the file is readable, if yes, slurp its contents,
# split on white spaces and return a list reference.
sub get_lines_as_list {
    my $self = shift;
    my $file_contents;
    if(! -r $self->{full_file_path}) {
        confess("File not readable!");
    }
    {
        local $/ = undef;
        open my $fh, $self->{full_file_path} or confess("Unable to open file: $!");
        $file_contents = <$fh>;
        close $fh;
    }
    # Split the slurped file into a list where each element is an rs ID.
    my @lines = split(/\s+/, $file_contents);
    return \@lines;
}
1;